export const Ipfs = {
  SAVE_SCENE_REQUESTED: 'SAVE_SCENE_REQUESTED',
  SAVE_SCENE_SUCCEEDED: 'SAVE_SCENE_SUCCEEDED',
  SAVE_SCENE_FAILED: 'SAVE_SCENE_FAILED',
  IPNS_BIND_REQUESTED: 'IPNS_BIND_REQUESTED',
  IPNS_BIND_SUCCEEDED: 'IPNS_BIND_SUCCEEDED',
  IPNS_BIND_FAILED: 'IPNS_BIND_FAILED'
};

export const Meta = {
  LOAD_META_REQUESTED: 'LOAD_META_REQUESTED',
  LOAD_META_SUCCEEDED: 'LOAD_META_SUCCEEDED',
  LOAD_META_FAILED: 'LOAD_META_FAILED',
  PUBLISH_META_REQUESTED: 'PUBLISH_META_REQUESTED',
  PUBLISH_META_SUCCEEDED: 'PUBLISH_META_SUCCEEDED',
  PUBLISH_META_FAILED: 'PUBLISH_META_FAILED'
};
