export const Ipfs = {
  SAVE_SCENE_REQUESTED: 'SAVE_SCENE_REQUESTED',
  SAVE_SCENE_SUCCEEDED: 'SAVE_SCENE_SUCCEEDED',
  SAVE_SCENE_FAILED: 'SAVE_SCENE_FAILED',
  IPNS_BIND_REQUESTED: 'IPNS_BIND_REQUESTED',
  IPNS_BIND_SUCCEEDED: 'IPNS_BIND_SUCCEEDED',
  IPNS_BIND_FAILED: 'IPNS_BIND_FAILED'
};
